
# general settings
import = [ "~/.config/alacritty/themes/tokyo-night.toml" ]
live_config_reload = true

# [shell]
# program = "/usr/bin/zsh"

[window]
dimensions = { columns = 110 , lines = 50 }
padding = { x = 5 , y = 0 }
dynamic_padding =  true
opacity = 1.0
decorations = "None"

[font]
normal = { family = "HackNerdFontMono", style = "Regular" }
size = 14
