
# general settings
import = [ "~/.config/alacritty/themes/tokyo-night.toml" ]
live_config_reload = true

# [shell]
# program = "/usr/bin/zsh"

[window]
dimensions = { columns = 110 , lines = 50 }
padding = { x = 10 , y = 10 }
opacity = 1.0
decorations = "None"

[font]
size = 14
